import { jsPDF } from "jspdf";
import { ptLabel, formatPhone, divisionMeta, toViewPeriod } from "./constants";

// ── Brand colours ──────────────────────────────────────────────────────────
const NAVY   = [11, 36, 71];    // --navy-900
const GOLD   = [180, 140, 60];  // --gold-600
const GOLD_L = [245, 220, 140]; // --gold-300
const INK    = [60, 70, 90];
const INK_L  = [130, 140, 160];
const PAPER  = [252, 251, 248];
const LINE   = [220, 218, 210];
const WHITE  = [255, 255, 255];
const NAVY_M = [22, 58, 110];   // --navy-700 for buyer accent
const TEAL   = [28, 110, 100];  // seller accent

const W = 210; // A4 width mm
const M = 18;  // margin

function header(doc, brokerName) {
  // Navy top bar
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, W, 22, "F");

  // Gold accent stripe
  doc.setFillColor(...GOLD);
  doc.rect(0, 22, W, 2, "F");

  // Brand wordmark
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(...WHITE);
  doc.text("Deal", M, 14.5);
  const dw = doc.getTextWidth("Deal");
  doc.setTextColor(...GOLD_L);
  doc.text("Knot", M + dw, 14.5);

  // Broker name right-aligned
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...GOLD_L);
  const bLabel = brokerName ? `Broker: ${brokerName}` : "";
  doc.text(bLabel, W - M, 14.5, { align: "right" });

  return 30; // y after header
}

function footer(doc) {
  const pageH = doc.internal.pageSize.getHeight();
  doc.setFillColor(...NAVY);
  doc.rect(0, pageH - 12, W, 12, "F");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(...GOLD_L);
  doc.text("Generated by DealKnot — dealknot.live", W / 2, pageH - 4.5, { align: "center" });
  doc.setTextColor(...INK_L);
}

function sectionLabel(doc, y, text) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  doc.setTextColor(...GOLD);
  doc.text(text.toUpperCase(), M, y);
  return y + 5;
}

function divider(doc, y) {
  doc.setDrawColor(...LINE);
  doc.setLineWidth(0.3);
  doc.line(M, y, W - M, y);
  return y + 4;
}

function personBlock(doc, y, person, role, accentColor, priceLabel, priceText, isRental) {
  const bw = (W - M * 2);
  const blockH = 52;

  // Card background
  doc.setFillColor(248, 248, 252);
  doc.roundedRect(M, y, bw, blockH, 3, 3, "F");
  doc.setDrawColor(...LINE);
  doc.setLineWidth(0.25);
  doc.roundedRect(M, y, bw, blockH, 3, 3, "S");

  // Left accent bar
  doc.setFillColor(...accentColor);
  doc.roundedRect(M, y, 3, blockH, 2, 2, "F");

  // Avatar circle
  const avatarX = M + 12;
  const avatarY = y + blockH / 2;
  doc.setFillColor(...accentColor);
  doc.circle(avatarX, avatarY, 8, "F");
  const initStr = (person.name || "")
    .split(" ").filter(Boolean).slice(0, 2).map((p) => p[0]).join("").toUpperCase();
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(...WHITE);
  doc.text(initStr, avatarX, avatarY + 3.2, { align: "center" });

  const tx = M + 24;

  // Role badge
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  doc.setTextColor(...accentColor);
  doc.text(role.toUpperCase(), tx, y + 8);

  // Name
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(...NAVY);
  doc.text(person.name || "", tx, y + 16);

  // Area + country
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...INK);
  doc.text(`📍 ${person.area || ""}`, tx, y + 23);

  // Phone
  doc.setFontSize(8.5);
  doc.setTextColor(...INK_L);
  doc.text(`${person.dial || ""} ${formatPhone(person.phone || "")}`, tx, y + 30);

  // Property type tag
  const typeText = ptLabel(person.type);
  doc.setFillColor(...NAVY);
  const tw = doc.getTextWidth(typeText) + 6;
  doc.roundedRect(tx, y + 34, tw, 6, 1, 1, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  doc.setTextColor(...WHITE);
  doc.text(typeText, tx + 3, y + 38.5);

  // Price (right side)
  const priceX = W - M - 4;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  doc.setTextColor(...INK_L);
  doc.text(priceLabel, priceX, y + 10, { align: "right" });
  doc.setFontSize(13);
  doc.setTextColor(...NAVY);
  doc.text(priceText, priceX, y + 20, { align: "right" });

  // Notes
  if (person.notes) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8);
    doc.setTextColor(...INK_L);
    const wrapped = doc.splitTextToSize(`Notes: ${person.notes}`, bw - 28);
    doc.text(wrapped[0], tx, y + 45); // one line max in compact block
  }

  return y + blockH + 6;
}

// ── Match Report ───────────────────────────────────────────────────────────
export function exportMatchPDF(match, displayCur, viewPeriod, brokerName) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const meta = divisionMeta(match.buyer.division);
  const isRental = match.buyer.division === "rentals";

  let y = header(doc, brokerName);

  // Report title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(...NAVY);
  doc.text("Match Report", M, y + 8);

  // Score badge (top right)
  const scoreX = W - M - 28;
  doc.setFillColor(...(match.kind === "stretch" ? [200, 140, 30] : NAVY));
  doc.roundedRect(scoreX, y, 28, 14, 3, 3, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...WHITE);
  doc.text(`${match.score}%`, scoreX + 14, y + 8.5, { align: "center" });
  doc.setFontSize(7);
  doc.text("match fit", scoreX + 14, y + 13, { align: "center" });

  // Sub info
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...INK_L);
  const dateStr = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
  doc.text(`${meta.label} · ${match.kind === "stretch" ? "Stretch match" : "Standard match"} · Generated ${dateStr}`, M, y + 17);

  y = divider(doc, y + 22);

  // Buyer block
  y = sectionLabel(doc, y, `${meta.buyerRole} Brief`);
  const buyerPrice = isRental
    ? `Budget (${viewPeriod || match.buyer.period || "monthly"})`
    : "Budget range";
  const buyerPriceText = isRental
    ? `${match.buyer.cur} ${(toViewPeriod(match.buyer.min, match.buyer.period, viewPeriod) / 1000).toFixed(0)}K – ${(toViewPeriod(match.buyer.max, match.buyer.period, viewPeriod) / 1000).toFixed(0)}K/${viewPeriod === "yearly" ? "yr" : "mo"}`
    : `${match.buyer.cur} ${(match.buyer.min / 1000).toFixed(0)}K – ${(match.buyer.max / 1000).toFixed(0)}K`;
  y = personBlock(doc, y, match.buyer, meta.buyerRole, NAVY_M, buyerPrice, buyerPriceText, isRental);

  // VS divider
  doc.setFillColor(...GOLD);
  doc.circle(W / 2, y, 5, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(...WHITE);
  doc.text("⇅", W / 2, y + 2.8, { align: "center" });
  y += 12;

  // Seller block
  y = sectionLabel(doc, y, `${meta.sellerRole} Listing`);
  const sellerLabel = isRental ? `Asking rent (${viewPeriod || match.seller.period || "monthly"})` : "Asking price";
  const sellerPriceText = isRental
    ? `${match.seller.cur} ${(toViewPeriod(match.seller.price, match.seller.period, viewPeriod) / 1000).toFixed(0)}K/${viewPeriod === "yearly" ? "yr" : "mo"}`
    : `${match.seller.cur} ${(match.seller.price / 1000).toFixed(0)}K`;
  y = personBlock(doc, y, match.seller, meta.sellerRole, TEAL, sellerLabel, sellerPriceText, isRental);

  y = divider(doc, y + 2);

  // Why it matches section
  y = sectionLabel(doc, y, "Why this match works");
  const reasons = [
    `✓  Same area — ${match.buyer.area}`,
    `✓  Same property type — ${ptLabel(match.buyer.type)}`,
    match.kind === "stretch"
      ? `✓  Stretch match — seller asks up to 25% above buyer's max budget`
      : `✓  Asking price within buyer's budget`,
  ];
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...INK);
  reasons.forEach((r) => {
    doc.text(r, M + 2, y);
    y += 6;
  });

  footer(doc);

  const safeName = `${match.buyer.name.split(" ")[0]}-${match.seller.name.split(" ")[0]}`.replace(/[^a-z0-9-]/gi, "");
  doc.save(`DealKnot-Match-${safeName}.pdf`);
}

// ── Listings Export ────────────────────────────────────────────────────────
export function exportListingsPDF(list, kind, division, brokerName, displayCur) {
  const doc = new jsPDF({ unit: "mm", format: "a4", orientation: "landscape" });
  const meta = divisionMeta(division);
  const role = kind === "buyers" ? meta.buyerRole : meta.sellerRole;
  const PW = 297; // landscape width

  let y = header(doc, brokerName);

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(...NAVY);
  doc.text(`${meta.label} ${role}s — Listings Export`, M, y + 8);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(...INK_L);
  const dateStr = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
  doc.text(`${list.length} contacts · Generated ${dateStr}`, M, y + 15);
  y += 22;

  // Table header
  const cols = kind === "buyers"
    ? ["#", "Name", "Status", "Country", "Area", "Type", "Min Budget", "Max Budget", "Phone", "Matches"]
    : ["#", "Name", "Status", "Country", "Area", "Type", "Asking Price", "Phone", "Matches"];
  const colW = kind === "buyers"
    ? [8, 38, 16, 28, 34, 22, 24, 24, 28, 18]
    : [8, 42, 16, 28, 38, 24, 26, 32, 22];

  const tableW = PW - M * 2;
  let x = M;

  // Header row background
  doc.setFillColor(...NAVY);
  doc.rect(M, y, tableW, 9, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  doc.setTextColor(...GOLD_L);
  cols.forEach((col, i) => {
    doc.text(col, x + 2, y + 6);
    x += colW[i];
  });
  y += 9;

  // Rows
  list.forEach((p, idx) => {
    if (y > 175) { // landscape A4 usable height ~185mm
      doc.addPage();
      y = 16;
      // Repeat header on new page
      x = M;
      doc.setFillColor(...NAVY);
      doc.rect(M, y, tableW, 9, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(7.5);
      doc.setTextColor(...GOLD_L);
      cols.forEach((col, i) => { doc.text(col, x + 2, y + 6); x += colW[i]; });
      y += 9;
    }

    const isBuyer = kind === "buyers";
    const rowH = 8;
    const even = idx % 2 === 0;

    // Row background
    doc.setFillColor(even ? 250 : 245, even ? 250 : 248, even ? 252 : 250);
    doc.rect(M, y, tableW, rowH, "F");

    x = M;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(...INK);

    const priceStr = isBuyer
      ? `${p.cur} ${(p.min / 1000).toFixed(0)}K`
      : `${p.cur} ${(p.price / 1000).toFixed(0)}K`;
    const maxStr = isBuyer ? `${p.cur} ${(p.max / 1000).toFixed(0)}K` : "";
    const labelMeta = { hot: "🔥 Hot", active: "✅ Active", warm: "⏳ Warm", cold: "💤 Cold", closed: "✔ Closed" };

    const cells = isBuyer
      ? [
          String(idx + 1),
          p.name,
          labelMeta[p.label] || p.label,
          p.country,
          p.area,
          ptLabel(p.type),
          priceStr,
          maxStr,
          `${p.dial} ${p.phone}`,
          String(p._matchCount || 0),
        ]
      : [
          String(idx + 1),
          p.name,
          labelMeta[p.label] || p.label,
          p.country,
          p.area,
          ptLabel(p.type),
          priceStr,
          `${p.dial} ${p.phone}`,
          String(p._matchCount || 0),
        ];

    cells.forEach((cell, i) => {
      const maxW = colW[i] - 3;
      const txt = doc.splitTextToSize(String(cell), maxW)[0] || "";
      doc.text(txt, x + 2, y + 5.5);
      x += colW[i];
    });

    // Row bottom border
    doc.setDrawColor(...LINE);
    doc.setLineWidth(0.15);
    doc.line(M, y + rowH, M + tableW, y + rowH);
    y += rowH;
  });

  // Outer table border
  doc.setDrawColor(...NAVY_M);
  doc.setLineWidth(0.4);
  doc.rect(M, 30 + 22, tableW, y - (30 + 22), "S");

  footer(doc);

  const safeDivision = division.charAt(0).toUpperCase() + division.slice(1);
  doc.save(`DealKnot-${safeDivision}-${role}s.pdf`);
}
